#pragma once

#include <array>
#include <random>
#include <vector>

#include "common.h"

class Simulation; // Forward declaration

/**
 * @class ExchangeMove
 * @brief Monte Carlo move that regrows the last m beads of a block of k consecutive particles so that
 * their ring polymers close onto themselves (identity), onto the next particle of the block (forward
 * cycle) or onto the previous one (backward cycle).
 *
 * Motivation: in bosonic PIMD the exchange sector is encoded in the smooth effective potential V_B, but
 * a molecular dynamics trajectory of hard-core particles has to pass through configurations with a
 * stretched exterior link (or overlapping cores) to switch closure, a free-energy barrier that grows
 * with the number of beads. This move jumps directly between sectors, as the swap move of the worm
 * algorithm does in PIMC. Pair swaps alone (k = 2) can only create products of 2-cycles when the MD is
 * frozen; blocks with k up to `exchange_kmax` make longer cycles reachable.
 *
 * Proposal: pick a block of k consecutive labels (a, ..., a+k-1) with 2 <= k <= kmax (where the quadratic
 * algorithm assigns exchange weight), a segment length m (1 <= m <= max_segment) and a closure tau from
 * T_k = {identity, forward cycle} (k = 2) or {identity, forward, backward} (k >= 3), uniformly. Every
 * particle i of the block has beads P-m..P-1 regrown as a free-particle (Levy) bridge from its anchor
 * (bead P-m-1) towards the unwrapped target anchor_i + MIC(end_{tau,i} - anchor_i), end_{tau,i} being
 * the first bead of the particle it closes onto (with winding-sum springs an image shift of the target
 * is drawn from the periodic free propagator). The proposal density of a segment is the mixture over
 * tau of the bridge densities; the interior spring energies cancel against the target distribution, so
 *
 *   A = min{1, exp(-beta_P [dU + dV_B]) * S(old) / S(new) },
 *   S(seg) = sum_tau exp(-beta_P [E_close,tau(seg) - g_tau]),
 *
 * with E_close,tau the energy of the RAW closing links last_i -> target_{tau,i} (a wrapped old segment
 * cannot be regenerated by a bridge to the nearest image and gets the density of a stretched link),
 * g_tau the free-propagator energies of the anchor-to-target displacements over m+1 links, dU the change
 * of the physical potential on the regrown slices and dV_B the change of the bosonic exterior potential.
 * Momenta are untouched, so detailed balance holds for the joint distribution.
 *
 * Communication (one rank per bead): the block's paths are gathered on all ranks (MPI_Allgather of
 * kmax x NDIM doubles per rank); rank 0 draws the proposal and broadcasts it; ranks holding regrown beads
 * evaluate dU for their slice (MPI_Reduce to rank 0); rank 0 evaluates dV_B with the proposed last beads
 * and broadcasts the decision; accepted proposals are applied and the forces recomputed.
 */
class ExchangeMove {
public:
    ExchangeMove(Simulation& _sim, int max_segment, int attempts, int kmax, unsigned int seed);

    /// Attempts the move(s); must be called by all ranks at the same point of the MD step.
    void attempt();

    double acceptanceRatio() const;
    long numTrials() const { return n_trials; }
    long numAccepted() const { return n_accepted; }

private:
    using Vec = std::array<double, NDIM>;

    void gatherPaths(const std::vector<int>& block);
    void levyBridge(const Vec& start, const Vec& target, int m, std::vector<Vec>& out);
    Vec bridgeTarget(const Vec& anchor, const Vec& end, int m, bool draw_image);
    double slicePotentialChange(const std::vector<int>& block, const std::vector<Vec>& new_pos) const;
    void separation(const Vec& x1, const Vec& x2, Vec& diff) const;
    double closingEnergy(const Vec& last, const Vec& target) const;
    double propagatorEnergy(const Vec& anchor, const Vec& end, int m) const;
    static int closureTarget(int i, int k, int tau);

    Simulation& sim;
    int max_segment;
    int n_attempts;
    int kmax;
    std::mt19937 gen;
    long n_trials;
    long n_accepted;

    // Full paths of the block particles (paths[i][bead]), identical on all ranks after gatherPaths()
    std::vector<std::vector<Vec>> paths;
    std::vector<double> gather_buffer;
    std::vector<double> proposal_buffer;
};
